### ISSUE TITLE
The referenced JSON file in the Oracle Dockerfile does not exist.

### ISSUE THREAD

**Issue by script-money** [galadriel-ai/contracts#91]
https://github.com/galadriel-ai/contracts/blob/8e49a70742f6dc4edb20fced21a3805fd55e40df/oracles/Dockerfile#L4

**Comment by KasparPeterson** [comment]
Thanks for the report.
This is the credentials file used to upload image generation results to the bucket for faster access compared to IPFS.

The oracles folder is not meant to be run by users and it's a reference to verify that our oracle runs as expected.

Do you want to run the oracle in docker for local testing?

**Comment by script-money** [comment]
> Thanks for the report. This is the credentials file used to upload image generation results to the bucket for faster access compared to IPFS.
> 
> The oracles folder is not meant to be run by users and it's a reference to verify that our oracle runs as expected.
> 
> Do you want to run the oracle in docker for local testing?

I attempted to use Docker but encountered missing files, hence I raised this issue. It is feasible to set up a venv to execute.
